spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/payment_service_db?createDatabaseIfNotExist=true
    username: root
    password: root

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port : 8081