spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/payment_service_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true

server:
  port : 8081