spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_db?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

  jpa:
    show-sql: true